[assembly: InternalsVisibleTo("SourceGeneratorSample.Greeting")]
[assembly: InternalsVisibleTo("SourceGeneratorSample.MyTuple")]
[assembly: InternalsVisibleTo("SourceGeneratorSample.IncrementalGenerator.Starters")]
[assembly: InternalsVisibleTo("AutoDeconstructMethodGenerator")]
[assembly: InternalsVisibleTo("AutoOverridding")]
[assembly: InternalsVisibleTo("MyTuple")]